config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources "artifacts", only: [:index, :show] do
      collection { post :search, to: 'artifacts#search' }
    end
  end
  
  resources "artifacts", only: [:index, :show] do
    collection { post :search, to: 'artifacts#search' }
  end

  get 'artifacts/index'
  get 'welcome/advanced_search'
  get 'artifacts/show'
  get 'welcome/index'
  get 'welcome/recherche'
  get "welcome/download_pdf"
  get "welcome/download_jpeg" => 'welcome#download_jpeg'

  root 'welcome#index'
  get "*path" => redirect("/")
end

app/models/artifact.rb
class Artifact
  include Mongoid::Document
  include Mongoid::Timestamps
  field :height, type: Integer
  field :width, type: Integer
  field :art_dataset_name, type: String
  field :art_location, type: String
  field :discipline_en, type: String
  field :discipline_fr, type: String
  field :catalogue_number, type: String
  field :image_original, type: String
  field :image_thumbnail, type: String
  field :artifact_group_en, type: String
  field :artifact_group_fr, type: String
  field :artifact_category_en, type: String
  field :artifact_category_fr, type: String
  field :artifact_sub_category_en, type: String
  field :artifact_sub_category_fr, type: String
  field :artifact_composition_general_en, type: String
  field :artifact_composition_general_fr, type: String
  field :artifact_composition_specific_en, type: String
  field :artifact_composition_specific_fr, type: String
  field :artifact_date, type: String
  field :objname_en, type: String
  field :objname_fr, type: String
  field :artifact_references, type: String

  paginates_per 50
  max_paginates_per 50
  #default_scope { order('height ASC') }

  def self.recherche(query)
    #where("objname like ?", "%#{query}%") 
  end

  def self.landscape
    return self.width > self.height
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :set_locale
 
 def default_url_options(options={})
  { locale: I18n.locale }
end


 protected
def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end

end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show]

  respond_to :html
  respond_to :json

def index
    @search = Artifact.search(params[:q])
    if(!params[:q].nil?)
    @search = Artifact.search(params[:q])
    @artifacts = @search.result.page(params[:page]).per(25)
 @search.build_condition if @search.conditions.empty?
@search.build_sort if @search.sorts.empty?
    respond_with(@artifacts)
  else
    @artifacts = Artifact.page(params[:page]).per(25)
    respond_with(@artifacts)
  end
=begin
  if params[:search]
    @artifacts = Artifact.recherche(params[:search]).page(params[:page]).per(25)
    respond_with(@artifacts)
    #render layout: "bienvenue"
  else
    @artifacts = Artifact.readonly.all.page(params[:page]).per(25)
    respond_with(@artifacts)
    #render layout: "bienvenue"
  end
=end
end




  def show
    #offset = rand(Artifact.count)
    #@artifact = Artifact.offset(offset).first
    @artifact
    render layout: "main"
  end

  def new
    @artifact = Artifact.new
    respond_with(@artifact)
  end

  def edit
  end

  def create
    @artifact = Artifact.new(artifact_params)
    @artifact.save
    respond_with(@artifact)
  end

  def update
    @artifact.update(artifact_params)
    respond_with(@artifact)
  end

  def destroy
    @artifact.destroy
    respond_with(@artifact)
  end

  private
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    def artifact_params
      params.require(:artifact).permit(:height, :width, :art_dataset_name, :art_location, :discipline_en, :discipline_fr, :catalogue_number, :image_original, :image_thumbnail, :artifact_group_en, :artifact_group_fr, :artifact_category_en, :artifact_category_fr, :artifact_sub_category_en, :artifact_sub_category_fr, :artifact_composition_general_en, :artifact_composition_general_fr, :artifact_composition_specific_en, :artifact_composition_specific_fr, :artifact_date, :objname_en, :objname_fr, :artifact_references)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_action :set_artefact, only: [:download_jpeg]

  respond_to :html


  def index
    @search = Artifact.search(params[:q])
    render layout: "essaie"
  end

  def download_pdf
  	#Doesnt need the pdf .. this is extra in this project
    send_file(
      "#{Rails.root}/public/your_file.pdf",
      filename: "your_custom_file_name.pdf",
      type: "application/pdf"
    )
  end

#advance multi-select form
=begin
def advanced_search
    @search = Artifact.search(params[:q])
    if(!params[:q].nil?)
    @search = Artifact.search(params[:q])
    @artifacts = @search.result.page(params[:page]).per(25)
 @search.build_condition if @search.conditions.empty?
@search.build_sort if @search.sorts.empty?
    respond_with(@artifacts)
  else
    @search.build_condition if @search.conditions.empty?
    @artifacts = Artifact.page(params[:page]).per(25)
    respond_with(@artifacts)
  end
end
=end

def advanced_search
@search = Artifact.search(params[:q])
#@search.build_condition
    @artifacts = @search.result
end

  def download_jpeg
    #http://localhost:3000/welcome/download_jpeg?id=54e9251b6775695f04295f00&locale=fr
    parameters = params.keys

    if parameters.include?('id')  #params must only accept 'id'
    	require 'open-uri'
      @artefact = Artifact.where(:id => params[:id]).first
    	url = @artefact.image_original
      filename = 'can-tech-museum-' + @artefact.catalogue_number + ".jpg"#url.split('/')[-1]
    	begin
        data = open(url).read
    	  send_data data, :disposition => 'attachment', :filename => filename
      rescue OpenURI::HTTPError
        url = 'http://source.techno-science.ca/images/1986.0468.001.aa.cs.jpg'
        data = open(url).read
        send_data data, :disposition => 'attachment', :filename => 'wrong-parameter.jpeg'
      end
    else
      #send a random image
      require 'open-uri'
      url = 'http://source.techno-science.ca/images/1986.0468.001.aa.cs.jpg'
      data = open(url).read
      send_data data, :disposition => 'attachment', :filename => 'wrong-parameter.jpeg'
    end
  end

  def recherche
     @search = Artifact.search(params[:q])
    if(!params[:q].nil?)
    @search = Artifact.search(params[:q])
    @artifacts = @search.result
    @search.build_condition
    respond_with(@artifacts)
  else
    @artifacts = Artifact.limit(40)
  end

  end




end

app/helpers/application_helper.rb
module ApplicationHelper


 def language_selector
		if I18n.locale == :en
			link_to "Fr", url_for(:locale => 'fr'), :class => "btn btn-info", :target=>"_blank"
		else
			link_to "En", url_for(:locale => 'en'), :class => "btn btn-info", :target=>"_blank"
		end
 end 

end

app/views/artifacts/index.html.erb
<style type="text/css">
  .loader {
  position: fixed;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  z-index: 9999;
  background: url('http://smallenvelop.com/wp-content/uploads/2014/08/Preloader_3.gif') 50% 50% no-repeat rgb(249,249,249);
}
</style>

<%= paginate @artifacts,  :outer_window => 4, :window =>  4  %>

<% 
#application helper
@composition = []
locale_en = (I18n.locale).to_s.eql?("en")
if !@artifacts.nil? 
@artifacts.each do |artefact| 
    if locale_en
    materiaux = eval(artefact.artifact_composition_general_en)
  else
    materiaux = eval(artefact.artifact_composition_general_fr)
  end
    if materiaux.size > 0
      materiaux.each do |mat|
        if !mat.eql?('[]')
          @composition.append(mat.split.collect { |w| w }.join('_'))
          @composition.uniq!
        end
      end
    end
  end
end

#li-helper

def find_materiaux(materiaux_value)
  materiaux_value = eval(materiaux_value)
  @obj_composition =[]
  if materiaux_value.size > 0
    materiaux_value.each do |mat|
      if !mat.eql?('[]')
        @obj_composition.append(mat.split.collect { |w| w }.join('_'))
      end
    end#do
  else
    return ' '
  end#if > 0
  return @obj_composition.join(' ')
end

  %>




<%
group =[]
@artifacts.each do |artefact|
if locale_en
  artefact = eval(artefact.artifact_group_en)
else
  artefact = eval(artefact.artifact_group_fr)
end
artefact.each {|n| group.push(n.split.collect { |w| w }.join('_')) if !n.empty?}

end
@group_artifact = group.uniq!
%>
<% 

def find_group(art_group)
artefact = []
art_group = eval(art_group)
art_group.each do |n|
    artefact.append(n.split.collect { |w| w }.join('_'))
end
return artefact.join(" ")
end
 %>



<section class="cd-gallery">

      <ul>
                
          <% 
          compte = 0
          @artifacts.each do |artefact| 
            compte = compte + 1
            %>

    <% if locale_en %>
            <li class="mix <%= find_group(artefact.artifact_group_en) %>  <%= obj = find_materiaux(artefact.artifact_composition_general_en) %>">

            <%= link_to (image_tag "#{artefact.image_original}", :tag =>"Image ", :class => "emr example#{compte}"), artefact %>
            <div class="show-title" style="background-color:white; padding:5px; margin: auto 0;">
              <h5><%= artefact.objname_en %></h5>

      <% else %>
            <li class="mix <%= find_group(artefact.artifact_group_fr) %>  <%= obj = find_materiaux(artefact.artifact_composition_general_fr) %>">


            <%= link_to (image_tag "#{artefact.image_original}", :tag =>"Image ", :class => "emr example#{compte}"), artefact %>
            <div class="show-title" style="background-color:white; padding:5px; margin: auto 0;">
              <h5><%= artefact.objname_fr %></h5>
     <% end %>

            </div>
            </li>
            <% end %>
        <li class="gap"></li>
        <li class="gap"></li>
        <li class="gap"></li>
      </ul>
      <div class="cd-fail-message"><%= I18n.t '.r_no_result'  %></div>
    </section> <!-- cd-gallery -->

    <%= render "shared/facets", foo: @composition, baz: @group_artifact %>

    <div class="loader"></div>

    <script type="text/javascript">
$(window).load(function() {
  $(".loader").fadeOut("slow");
})
</script>

app/views/artifacts/index_backup.html.erb
<h1>Listing artifacts</h1>
<style type="text/css">
  .imga{
    max-height: 210px;
  }
</style>

<%= paginate @artifacts %>

<%= form_tag(artifacts_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Image link</th>
      <!--
      <th>Objtype</th>
      <th>About</th>
      <th>Uid</th>
      -->
      <th>Image thumbnail</th>
      <th>Color</th>
      <th>Height</th>
      <th>Width</th>
      <th>Landscape</th>
      <th>Objname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artefact| %>
      <tr>
        <td><%= artefact.image_link %></td>
        <!--
        <td><%= artefact.objtype %></td>
        <td><%= artefact.about %></td>
        <td><%= artefact.uid %></td>
        -->
        <td><%#= image_tag "http://source.techno-science.ca/images/#{artefact.image_link}", :class => 'imga'%></td>
        <td><%= artefact.color %></td>
        <td><%= artefact.height %></td>
        <td><%= artefact.width %></td>
        <td><%= artefact.landscape %></td>
        <td><%= artefact.objname %></td>
        <td><%= link_to 'Show', artefact %></td>
        <td><%#= link_to 'Edit', edit_artefact_path(artefact) %></td>
        <td><%#= link_to 'Destroy', artefact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<style type="text/css">
  .imgur{
    position: relative;
    float: left;
    width:  100px;
    height: 100px;
    background-position: 50% 50%;
    background-repeat:   no-repeat;
    background-size:     cover;
    margin: 2px;
    overflow:hidden;  
  }
</style>
<h4>Products</h4>
<% @artifacts.each do |artefact| %>
<%= image_tag "rb/#{artefact.image_link}", :class => 'imgur'%>

<% end %>
<%#= link_to 'New Artefact', new_artefact_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Artefacts', artefacts_path %></li>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="no-js">
<head>
  <meta charset="UTF-8">
  <title>Canada Science and Technology Museums Corporation | Code 2015 | Museum Image search Engine | Société des Musées de Sciences et Technologies du Canada </title>
  <meta name="author" content="Guinsly Mondésir">
  <meta name="description" content="#CODE2015 application hackathon">
  <%= favicon_link_tag 'favicon.ico' %>
     <meta name="keywords" content="Open data, Canada Science and Technology Museums Corporation, Jeu de données application, Homepage, Image, Artefact, Artifact, Canadian Artififact, Ottawa">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css"> <!-- CSS reset -->
 <%= stylesheet_link_tag    "cody" %>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script> <!-- Modernizr -->
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

 <style type="text/css">

.cd-header {
height: 150px;
}
</style>
    
  <title>Open Data Code2015 Jeux de données: Musée |  Museum Image search Engine </title>
  <style type="text/css">
   a.home:link {
    text-decoration: none;
    color:white;
}

 a.home:visited {
    text-decoration: none;
}

 a.home:hover {
    text-decoration: underline;
}

 a.home:active {
    text-decoration: none;
}
  </style>
</head>
<body>
  <header class="cd-header">
    <h1>
      <%= link_to "#{I18n.t '.r_home'}", root_path,  :class=>"home", :style =>"color:white" %>
    </h1>
  </header>




  <main class="cd-main-content">
    <div class="cd-tab-filter-wrapper">
      <div class="cd-tab-filter">
        <ul class="cd-filters">
          <li class="placeholder"> 
            <a data-type="all" href="#0">All</a> <!-- selected option on mobile -->
          </li> 
          <!--
          <li class="filter"><a class="selected" href="#0" data-type="all">All</a></li>
          <li class="filter" data-filter=".bw"><a href="#0" data-type="color-1">Black and White</a></li>
          <li class="filter" data-filter=".cl"><a href="#0" data-type="color-2">Color</a></li>
          -->
          <li class="filter">
          <% if current_page?(:controller => 'welcome', :action => 'advanced_search') %>
            <%= link_to "#{I18n.t '.adv_back'}", 'javascript:history.go(-1);' %>
          <% else %>
            <%= link_to "#{I18n.t '.r_advseach'}", welcome_advanced_search_url %>
          <% end %>
          </li>
        </ul> <!-- cd-filters -->
      </div> <!-- cd-tab-filter -->
    </div> <!-- cd-tab-filter-wrapper -->

<%= yield %>


  </main> <!-- cd-main-content -->

  

<%= javascript_include_tag 'mixitup'%>


  <script type="text/javascript">
  //credits http://codyhouse.co/gem/content-filter/
  //@guerriero_se thanks buddy!
jQuery(document).ready(function($){
  //open/close lateral filter
  $('.cd-filter-trigger').on('click', function(){
    triggerFilter(true);
  });
  $('.cd-filter .cd-close').on('click', function(){
    triggerFilter(false);
  });

  function triggerFilter($bool) {
    var elementsToTrigger = $([$('.cd-filter-trigger'), $('.cd-filter'), $('.cd-tab-filter'), $('.cd-gallery')]);
    elementsToTrigger.each(function(){
      $(this).toggleClass('filter-is-visible', $bool);
    });
  }

  //mobile version - detect click event on filters tab
  var filter_tab_placeholder = $('.cd-tab-filter .placeholder a'),
    filter_tab_placeholder_default_value = 'Select',
    filter_tab_placeholder_text = filter_tab_placeholder.text();
  
  $('.cd-tab-filter li').on('click', function(event){
    //detect which tab filter item was selected
    var selected_filter = $(event.target).data('type');
      
    //check if user has clicked the placeholder item
    if( $(event.target).is(filter_tab_placeholder) ) {
      alert('hello')
      (filter_tab_placeholder_default_value == filter_tab_placeholder.text()) ? filter_tab_placeholder.text(filter_tab_placeholder_text) : filter_tab_placeholder.text(filter_tab_placeholder_default_value) ;
      $('.cd-tab-filter').toggleClass('is-open');

    //check if user has clicked a filter already selected 
    } else if( filter_tab_placeholder.data('type') == selected_filter ) {
      filter_tab_placeholder.text($(event.target).text());
      $('.cd-tab-filter').removeClass('is-open'); 


    } else {
      //close the dropdown and change placeholder text/data-type value
      $('.cd-tab-filter').removeClass('is-open');
      filter_tab_placeholder.text($(event.target).text()).data('type', selected_filter);
      filter_tab_placeholder_text = $(event.target).text();
      
      //add class selected to the selected filter item
      $('.cd-tab-filter .selected').removeClass('selected');
      $(event.target).addClass('selected');
    }
  });
  
  //close filter dropdown inside lateral .cd-filter 
  $('.cd-filter-block h4').on('click', function(){
    $(this).toggleClass('closed').siblings('.cd-filter-content').slideToggle(300);
  })

  //fix lateral filter and gallery on scrolling
  $(window).on('scroll', function(){
    (!window.requestAnimationFrame) ? fixGallery() : window.requestAnimationFrame(fixGallery);
  });

  function fixGallery() {
    var offsetTop = $('.cd-main-content').offset().top,
      scrollTop = $(window).scrollTop();
    ( scrollTop >= offsetTop ) ? $('.cd-main-content').addClass('is-fixed') : $('.cd-main-content').removeClass('is-fixed');
  }

  /************************************
    MitItUp filter settings
    More details: 
    https://mixitup.kunkalabs.com/
    or:
    http://codepen.io/patrickkunka/
  *************************************/

  buttonFilter.init();
  $('.cd-gallery ul').mixItUp({
      controls: {
        enable: false
      },
      callbacks: {
        onMixStart: function(){
          $('.cd-fail-message').fadeOut(200);
        },
          onMixFail: function(){
            $('.cd-fail-message').fadeIn(200);
        }
      }
  });

  //search filtering
  //credits http://codepen.io/edprats/pen/pzAdg
  var inputText;
  var $matching = $();

  var delay = (function(){
    var timer = 0;
    return function(callback, ms){
      clearTimeout (timer);
        timer = setTimeout(callback, ms);
    };
  })();

  $(".cd-filter-content input[type='search']").keyup(function(){
      // Delay function invoked to make sure user stopped typing
      delay(function(){
        inputText = $(".cd-filter-content input[type='search']").val().toLowerCase();
        // Check to see if input field is empty
        if ((inputText.length) > 0) {            
            $('.mix').each(function() {
              var $this = $(this);
            
              // add item to be filtered out if input text matches items inside the title   
              if($this.attr('class').toLowerCase().match(inputText)) {
                  $matching = $matching.add(this);
              } else {
                  // removes any previously matched item
                  $matching = $matching.not(this);
              }
            });
            $('.cd-gallery ul').mixItUp('filter', $matching);
        } else {
            // resets the filter to show all item if input is empty
            $('.cd-gallery ul').mixItUp('filter', 'all');
        }
      }, 200 );
  });
});

/*****************************************************
  MixItUp - Define a single object literal 
  to contain all filter custom functionality
*****************************************************/
var buttonFilter = {
    // Declare any variables we will need as properties of the object
    $filters: null,
    groups: [],
    outputArray: [],
    outputString: '',
  
    // The "init" method will run on document ready and cache any jQuery objects we will need.
    init: function(){
      var self = this; // As a best practice, in each method we will asign "this" to the variable "self" so that it remains scope-agnostic. We will use it to refer to the parent "buttonFilter" object so that we can share methods and properties between all parts of the object.
    
      self.$filters = $('.cd-main-content');
      self.$container = $('.cd-gallery ul');
    
      self.$filters.find('.cd-filters').each(function(){
          var $this = $(this);
        
        self.groups.push({
            $inputs: $this.find('.filter'),
            active: '',
            tracker: false
        });
      });
      
      self.bindHandlers();
    },
  
    // The "bindHandlers" method will listen for whenever a button is clicked. 
    bindHandlers: function(){
      var self = this;

      self.$filters.on('click', 'a', function(e){
          self.parseFilters();
      });
      self.$filters.on('change', function(){
        self.parseFilters();           
      });
    },
  
    parseFilters: function(){
      var self = this;
   
      // loop through each filter group and grap the active filter from each one.
      for(var i = 0, group; group = self.groups[i]; i++){
        group.active = [];
        group.$inputs.each(function(){
          var $this = $(this);
          if($this.is('input[type="radio"]') || $this.is('input[type="checkbox"]')) {
            if($this.is(':checked') ) {
              group.active.push($this.attr('data-filter'));
            }
          } else if($this.is('select')){
            group.active.push($this.val());
          } else if( $this.find('.selected').length > 0 ) {
            group.active.push($this.attr('data-filter'));
          }
        });
      }
      self.concatenate();
    },
  
    concatenate: function(){
      var self = this;
    
      self.outputString = ''; // Reset output string
    
      for(var i = 0, group; group = self.groups[i]; i++){
          self.outputString += group.active;
      }
    
      // If the output string is empty, show all rather than none:    
      !self.outputString.length && (self.outputString = 'all'); 
  
      // Send the output string to MixItUp via the 'filter' method:    
    if(self.$container.mixItUp('isLoaded')){
        self.$container.mixItUp('filter', self.outputString);
    }
    }
};
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61032706-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canada Science and Technology Museums Corporation | Code 2015 | Museum Image search Engine | Société des Musées de Sciences et Technologies du Canada </title>
    <meta name="description" content="#CODE2015 application hackathon">
     <meta name="keywords" content="Open data, Canada Science and Technology Museums Corporation, Jeu de données application, Homepage, Image, Artefact, Artifact, Canadian Artififact, Ottawa">
     <%= favicon_link_tag 'favicon.ico' %>
    <meta name="author" content="Guinsly Mondésir">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
     <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed|Merriweather' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Francois+One|Shadows+Into+Light|Bree+Serif' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    
    <style type="text/css">
      section.header_name h3{
        font-family: 'Francois One', sans-serif;
      }
      section.header_name h3 span{
        font-family: 'Shadows Into Light', cursive;
      }
      section{
        margin: 0;
        padding: 0;
      }
      section.header_name{
        //background-color: #F99200;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
        text-align: left
        font-size:12px;
        //border-bottom: 1px dashed #666;
      }
    </style>
  </head>
  <body>
  
<section class="header_name">
    <h3 class="text-center">

    <%= link_to root_path do %>
  <%= I18n.t '.cstm_abbr' %> <%= I18n.t '.index_title' %> ::<span>&nbsp;<%= I18n.t '.shw_opd' %></a></span>
<% end %>
</h3>
</section>

  <div class="container">
       <%= render 'layouts/messages' %>
  </div>
       <%= yield %>


  </body>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61032706-1', 'auto');
  ga('send', 'pageview');

</script>

</html>